engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
    - src/scripts/app/**
exclude_paths:
  - node_modules/*
  - eslint-rules/*
  - src/scripts/libs/*
  - gulpfile.babel.js
  - safe-regex-shell.js
